### ISSUE TITLE
Help with proto folder

### ISSUE THREAD

**Issue by infiamit** [pokearaujo/multidevice#15]
I am trying to understand what is the use of proto folder and the binary.ts file there. 
The code is very minified. Is it possible to achieve same functionality from a npm package instead of using the proto folder for decoding frames from the whatsapp server.

**Comment by burstfreeze** [comment]
Proto is a standard like JSON but serialized.

Binary puts content in a format that WhatsApp expects. See https://medium.com/@pantelis/protecting-game-saves-and-the-case-of-unworthy-e24c8fd68e16 subsection "Suggestion 1. Binary Format." for an example. Binary formats are proprietary so there is no universal standard or npm package to use. And also in the Binary.ts you find some bit shifting https://stackoverflow.com/questions/141525/what-are-bitwise-shift-bit-shift-operators-and-how-do-they-work

Feel free to contribute if you think things could be put differently :)

**Comment by infiamit** [comment]
Thanks, i understand it now,
