### ISSUE TITLE
Need Callback function for QRCode

### ISSUE THREAD

**Issue by ramacatur** [pokearaujo/multidevice#16]
Can you give a callback for qrcode? Thanks

**Comment by pokearaujo** [comment]
try

`
session.on('qr', (qr) => {
       console.log('received qr', qr);
});
`

**Comment by ramacatur** [comment]
> try
> 
> 
> 
> `
> 
> session.on('qr', (qr) => {
> 
>        console.log('received qr', qr);
> 
> });
> 
> `

Thanks, I will try.

And is there a function that is used to check whether the mobile number is registered for whatsapp or not?

**Comment by pokearaujo** [comment]
See in #17  isOnWhatsApp

**Comment by ramacatur** [comment]
> See in #17 isOnWhatsApp

Thank you very much

**Comment by burstfreeze** [comment]
@ramacatur please close the issue if it's solved for you so the issue section gets cleaned up
