### ISSUE TITLE
cant start ! issue

### ISSUE THREAD

**Issue by MaznAbdullah** [pokearaujo/multidevice#3]
conn open
SEND TO SERVER 43
(node:20551) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined
    at p (/home/ajam/Desktop/multidevice-master/src/socket/NoiseHandshake.js:43:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20551) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20551) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined
    at /home/ajam/Desktop/multidevice-master/src/socket/NoiseHandshake.js:96:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
(node:20551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
received msg 256
FrameSocket.onFrame(253 bytes)
received server hello 1afa010a20c904dd762570229d76c75d1a87d8346a31a47eb3ab205fb7f3ff20a780b6e815123051b12fe28cdaee67c876fe84e785b617cc4d282100d7869cf824f43d5492f353829c27bb6af8cb68832bc1ae4acabcc81aa30199aa31f2918c54aec5c41d6516a099cfd8bd22591b4cc9d6937163fe9e048e05065d827039dacc8f95d6d8f69b226175cf69c9548fede8f5aadf208f672f17c5bf7d4dca765fb7772eb212391b6ad5fa62690ba5a2956e81a96f52c717e514e7988b9b3901f347ff024622a8f96a718c31d6d2d6a450854dc4040c855bfe8ab65a0700cac24a286e7b6ac580cc177818424ce4db70a241eed2ebd3ef6ae6c879d5a863
(node:20551) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
(node:20551) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined
    at /home/ajam/Desktop/multidevice-master/src/socket/NoiseHandshake.js:96:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
(node:20551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:20551) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subtle' of undefined
    at /home/ajam/Desktop/multidevice-master/src/socket/NoiseHandshake.js:96:27
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
(node:20551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
received msg 4
closed
FrameSocket closed

**Comment by pokearaujo** [comment]
Hello,

You need min node version v15

**Comment by mateusmirandaalmeida** [comment]
https://github.com/pokearaujo/multidevice/blob/master/README.md
I suggested you use the 16x version

**Comment by burstfreeze** [comment]
@MaznAbdullah please close the issue if the comments helped - to clean things up.
